# Generated by Django 3.2.7 on 2021-09-07 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('search_term', models.CharField(max_length=250)),
                ('interval_time', models.CharField(choices=[(2, '2 Mins'), (10, '10 Mins'), (30, '30 Mins')], default=2, max_length=2)),
            ],
            options={
                'unique_together': {('search_term', 'email')},
            },
        ),
    ]
