# Generated by Django 3.2.7 on 2021-09-07 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='interval_time',
            field=models.CharField(choices=[('2', '2 Mins'), ('10', '10 Mins'), ('30', '30 Mins')], default='2', max_length=2),
        ),
    ]
