# Generated by Django 3.2.7 on 2021-09-14 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0002_alter_alert_interval_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertCheapestProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cheapest_product', models.CharField(max_length=250)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('alert_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alert.alert')),
            ],
        ),
    ]
